namespace VisualForge.UI.Xaml.View.Control
{
    [default_interface]
    runtimeclass EditorDocumentControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        EditorDocumentControl();
        String Text{ get; };
        Int32 SelectionStart{ get; };
        Int32 SelectionLength{ get; };
        Int32 ScrollLine{ get; };
        Int32 ScrollColumn{ get; };
        void SetText(String text);
        void ReplaceSelection(String text);
        void Select(Int32 start, Int32 length);
        void SetScrollPosition(Int32 line, Int32 column);
        void FocusEditor();
        void SetBreakpoint(Int32 line, Boolean enabled);
        void SetDebugLine(Int32 line);
        void SetSemanticTokens(String tokenData);
        void SetDiagnosticLine(Int32 line, Boolean enabled);
        void ClearDiagnosticLines();
        void CopySelection();
        void CutSelection();
        Windows.Foundation.IAsyncAction PasteClipboardAsync();
        void SelectAllText();
        event Windows.Foundation.TypedEventHandler<Object, Object> TextChanged;
        event Windows.Foundation.TypedEventHandler<Object, Object> SelectionChanged;
        event Windows.Foundation.TypedEventHandler<Object, Object> CompletionRequested;
        event Windows.Foundation.TypedEventHandler<Object, Int32> BreakpointRequested;
    }
}
