namespace VisualForge.UI.Xaml.View.Control
{
    [default_interface]
    runtimeclass SolutionExplorerControl : Microsoft.UI.Xaml.Controls.UserControl
    {
        SolutionExplorerControl();
        void LoadWorkspace(String rootPath, String solutionPath);
        event Windows.Foundation.TypedEventHandler<Object, String> FileOpenRequested;
        event Windows.Foundation.TypedEventHandler<Object, String> ProjectSelectedRequested;
        event Windows.Foundation.TypedEventHandler<Object, String> ContextActionRequested;
        void SetStartupProject(String projectPath);
        void SetShowAllFiles(Boolean value);
        void SetFilter(String value);
    }
}
